---

name: static-analysis

on:
  push:
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
      - run: pip install yamllint flake8 bandit
      - run: yamllint -s .github/workflows/
        continue-on-error: true
      - run: flake8 coturn_exporter
        continue-on-error: true
      - run: bandit coturn_exporter
        continue-on-error: true

...
